name: Publish Docker image

on:
  push:
    branches:
      - main
      - multi-arch-test

jobs:
  push_to_registry:
    name: Push image to Docker Hub
    runs-on: ubuntu-20.04
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push amd64
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: |-
              linux/amd64
          file: ./Dockerfile
          build-args: multilib_version=gcc-multilib
          pull: true
          push: true
          cache-from: type=registry,ref=camerondurham/cs350-docker-multiarch:buildcache
          cache-to: type=registry,ref=camerondurham/cs350-docker-multiarch:buildcache,mode=max
          tags: camerondurham/cs350-docker-multiarch:v1
      -
        name: Build and push arm64
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: |-
              linux/arm64
          file: ./Dockerfile
          build-args: multilib_version=gcc-multilib-x86-64-linux-gnu
          pull: true
          push: true
          cache-from: type=registry,ref=camerondurham/cs350-docker-multiarch:buildcache
          cache-to: type=registry,ref=camerondurham/cs350-docker-multiarch:buildcache,mode=max
          tags: camerondurham/cs350-docker-multiarch:v1
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
